# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  test-node-backend-nopg:
    build:
      target: development
    image: test-node-backend-nopg-development
    container_name: test-node-backend-nopg-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
      
